CREATE TABLE [dbo].[Members] (
    [member_id]  INT          IDENTITY(1,1) NOT NULL,
    [last_name]  VARCHAR (20) NULL,
    [first_name] VARCHAR (20) NULL,
    [age]        INT          NULL,
    [rank]       VARCHAR (3)  NULL,
    [rank_value] INT          NULL,
    [sensei]     VARCHAR (20) NULL,
    [dojo]       VARCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([member_id] ASC)
);


CREATE TABLE [dbo].[Students] (
    [student_id]  INT          IDENTITY(1,1) NOT NULL,
    [last_name]   VARCHAR (20) NULL,
    [first_name]  VARCHAR (20) NULL,
    [age]         INT          NULL,
    [dojo]        VARCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([student_id] ASC)
);


INSERT INTO [dbo].[Students] ([last_name], [first_name], [age], [dojo]) 
VALUES 
('Smith', 'John', 25, 'Karate Dojo'),
('Johnson', 'Emily', 30, 'Taekwondo Dojo'),
('Williams', 'Michael', 22, 'Jiu-Jitsu Academy'),
('Brown', 'Sarah', 28, 'Aikido Dojo'),
('Miller', 'David', 35, 'Kendo Club'),
('Davis', 'Sophia', 21, 'Muay Thai Gym'),
('Martinez', 'Daniel', 31, 'Boxing Club'),
('Jones', 'Emma', 27, 'Wrestling Academy'),
('Garcia', 'Liam', 24, 'MMA Gym'),
('Rodriguez', 'Ava', 30, 'Tang Soo Do Dojo'),
('Hernandez', 'Olivia', 29, 'Judo Club'),
('Lopez', 'Ethan', 26, 'Hapkido Academy'),
('Gonzalez', 'Isabella', 23, 'Krav Maga Dojo'),
('Wilson', 'James', 32, 'Kickboxing Gym'),
('Anderson', 'Avery', 28, 'Wing Chun School'),
('Thomas', 'Mia', 31, 'Capoeira Center'),
('Taylor', 'Noah', 30, 'Tai Chi Studio'),
('Moore', 'Charlotte', 29, 'Escrima Dojo'),
('Jackson', 'Liam', 24, 'Boxing Club'),
('White', 'Harper', 25, 'Karate Dojo'),
('Harris', 'Ella', 26, 'Taekwondo Dojo'),
('Martin', 'Logan', 27, 'Jiu-Jitsu Academy'),
('Thompson', 'Sophia', 28, 'Aikido Dojo'),
('Garcia', 'Ethan', 29, 'Kendo Club'),
('Martinez', 'Mason', 30, 'Muay Thai Gym'),
('Robinson', 'Ava', 31, 'Boxing Club'),
('Clark', 'Daniel', 32, 'Wrestling Academy'),
('Rodriguez', 'Olivia', 33, 'MMA Gym'),
('Lewis', 'Elijah', 34, 'Tang Soo Do Dojo'),
('Lee', 'Mia', 35, 'Judo Club'),
('Walker', 'Ethan', 36, 'Hapkido Academy'),
('Hall', 'Isabella', 37, 'Krav Maga Dojo'),
('Allen', 'James', 38, 'Kickboxing Gym'),
('Young', 'Avery', 39, 'Wing Chun School'),
('Hernandez', 'Mia', 40, 'Capoeira Center'),
('King', 'Noah', 41, 'Tai Chi Studio'),
('Wright', 'Charlotte', 42, 'Escrima Dojo'),
('Scott', 'Liam', 43, 'Boxing Club'),
('Torres', 'Harper', 44, 'Karate Dojo'),
('Nguyen', 'Ella', 45, 'Taekwondo Dojo'),
('Hill', 'Logan', 46, 'Jiu-Jitsu Academy'),
('Flores', 'Sophia', 47, 'Aikido Dojo'),
('Green', 'Ethan', 48, 'Kendo Club'),
('Adams', 'Mason', 49, 'Muay Thai Gym'),
('Nelson', 'Ava', 50, 'Boxing Club'),
('Baker', 'Daniel', 51, 'Wrestling Academy'),
('Hall', 'Olivia', 52, 'MMA Gym'),
('Ramirez', 'Elijah', 53, 'Tang Soo Do Dojo'),
('Campbell', 'Mia', 54, 'Judo Club'),
('Thompson', 'Logan', 40, 'Judo Club'),
('White', 'Harper', 38, 'Karate Dojo'),
('Ramirez', 'Ella', 29, 'Taekwondo Dojo'),
('Scott', 'Lucas', 37, 'Jiu-Jitsu Academy'),
('Hill', 'Sophia', 36, 'Aikido Dojo'),
('Lopez', 'Ethan', 32, 'Kendo Club'),
('King', 'Olivia', 33, 'Muay Thai Gym'),
('Young', 'James', 25, 'Boxing Club'),
('Hernandez', 'Mia', 26, 'Wrestling Academy'),
('Clark', 'Elijah', 23, 'MMA Gym'),
('Gonzalez', 'Ava', 31, 'Tang Soo Do Dojo'),
('Carter', 'Noah', 30, 'Judo Club'),
('Adams', 'Sophia', 28, 'Karate Dojo'),
('Morales', 'Liam', 35, 'Taekwondo Dojo'),
('Nguyen', 'Ella', 34, 'Jiu-Jitsu Academy'),
('Perez', 'Oliver', 39, 'Aikido Dojo'),
('Hall', 'Harper', 38, 'Kendo Club'),
('Flores', 'Emma', 21, 'Muay Thai Gym'),
('Cook', 'Isabella', 29, 'Boxing Club'),
('Russell', 'Liam', 32, 'Wrestling Academy'),
('Bailey', 'Ava', 27, 'MMA Gym'),
('Butler', 'Daniel', 26, 'Tang Soo Do Dojo'),
('Barnes', 'Mia', 30, 'Judo Club'),
('Gutierrez', 'Logan', 31, 'Karate Dojo'),
('Sanders', 'Ella', 28, 'Taekwondo Dojo'),
('Perry', 'Sophia', 25, 'Jiu-Jitsu Academy'),
('Long', 'Ethan', 33, 'Aikido Dojo'),
('Price', 'Olivia', 37, 'Kendo Club'),
('Coleman', 'James', 24, 'Muay Thai Gym'),
('Reyes', 'Ava', 23, 'Boxing Club'),
('Howard', 'Elijah', 37, 'Wrestling Academy'),
('Washington', 'Mia', 29, 'MMA Gym'),
('Bryant', 'Sophia', 31, 'Tang Soo Do Dojo'),
('Ward', 'Lucas', 34, 'Judo Club'),
('Bell', 'Harper', 38, 'Karate Dojo'),
('Gomez', 'Olivia', 36, 'Taekwondo Dojo'),
('Kelly', 'Ella', 27, 'Jiu-Jitsu Academy'),
('Wood', 'Liam', 35, 'Aikido Dojo'),
('James', 'Isabella', 32, 'Kendo Club'),
('Watson', 'Emma', 39, 'Muay Thai Gym'),
('Brooks', 'Daniel', 28, 'Boxing Club'),
('Sanchez', 'Ava', 26, 'Wrestling Academy'),
('Rogers', 'Logan', 33, 'MMA Gym'),
('Morgan', 'Sophia', 31, 'Tang Soo Do Dojo'),
('Johnson', 'James', 37, 'Judo Club'),
('Reed', 'Harper', 38, 'Karate Dojo'),
('Bailey', 'Olivia', 29, 'Taekwondo Dojo'),
('Simmons', 'Ella', 30, 'Jiu-Jitsu Academy'),
('Foster', 'Lucas', 34, 'Aikido Dojo'),
('Perez', 'Isabella', 32, 'Kendo Club'),
('Bennett', 'Emma', 35, 'Muay Thai Gym');


INSERT INTO [dbo].[Members] ([last_name], [first_name], [age], [rank], [rank_value], [sensei], [dojo]) 
VALUES 
('Smith', 'John', 35, 'kyu', 6, 'Sensei Tom', 'Karate Dojo'),
('Johnson', 'Emily', 40, 'kyu', 5, 'Sensei Lee', 'Taekwondo Dojo'),
('Williams', 'Michael', 28, 'dan', 2, 'Sensei Rodriguez', 'Jiu-Jitsu Academy'),
('Brown', 'Sarah', 30, 'kyu', 4, 'Sensei Garcia', 'Aikido Dojo'),
('Miller', 'David', 37, 'dan', 1, 'Sensei Hernandez', 'Kendo Club'),
('Davis', 'Sophia', 31, 'kyu', 3, 'Sensei Martinez', 'Muay Thai Gym'),
('Martinez', 'Daniel', 38, 'dan', 1, 'Sensei Nguyen', 'Boxing Club'),
('Jones', 'Emma', 29, 'kyu', 5, 'Sensei Lopez', 'Wrestling Academy'),
('Garcia', 'Liam', 34, 'dan', 2, 'Sensei Thompson', 'MMA Gym'),
('Rodriguez', 'Ava', 36, 'kyu', 4, 'Sensei Clark', 'Tang Soo Do Dojo'),
('Hernandez', 'Olivia', 29, 'dan', 3, 'Sensei Miller', 'Judo Club'),
('Lopez', 'Ethan', 33, 'kyu', 6, 'Sensei Anderson', 'Hapkido Academy'),
('Gonzalez', 'Isabella', 27, 'dan', 1, 'Sensei Wilson', 'Krav Maga Dojo'),
('Wilson', 'James', 38, 'kyu', 4, 'Sensei Thomas', 'Kickboxing Gym'),
('Anderson', 'Avery', 32, 'dan', 2, 'Sensei Taylor', 'Wing Chun School'),
('Thomas', 'Mia', 31, 'kyu', 5, 'Sensei Moore', 'Capoeira Center'),
('Taylor', 'Noah', 39, 'dan', 1, 'Sensei Jackson', 'Tai Chi Studio'),
('Moore', 'Charlotte', 36, 'kyu', 3, 'Sensei White', 'Escrima Dojo'),
('Jackson', 'Liam', 30, 'dan', 2, 'Sensei Harris', 'Boxing Club'),
('White', 'Harper', 35, 'kyu', 6, 'Sensei Martin', 'Karate Dojo'),
('Harris', 'Ella', 28, 'dan', 1, 'Sensei Scott', 'Taekwondo Dojo'),
('Martin', 'Logan', 33, 'kyu', 4, 'Sensei Thompson', 'Jiu-Jitsu Academy'),
('Thompson', 'Sophia', 29, 'dan', 3, 'Sensei Davis', 'Aikido Dojo'),
('Garcia', 'Ethan', 37, 'kyu', 5, 'Sensei Gonzalez', 'Kendo Club'),
('Martinez', 'Mason', 32, 'dan', 2, 'Sensei Martinez', 'Muay Thai Gym'),
('Robinson', 'Ava', 30, 'kyu', 6, 'Sensei Robinson', 'Boxing Club'),
('Clark', 'Daniel', 36, 'dan', 1, 'Sensei Davis', 'Wrestling Academy'),
('Rodriguez', 'Olivia', 31, 'kyu', 3, 'Sensei Hernandez', 'MMA Gym'),
('Lewis', 'Elijah', 34, 'dan', 2, 'Sensei Rodriguez', 'Tang Soo Do Dojo'),
('Lee', 'Mia', 38, 'kyu', 4, 'Sensei Lee', 'Judo Club'),
('Walker', 'Ethan', 32, 'dan', 1, 'Sensei Thompson', 'Hapkido Academy'),
('Hall', 'Isabella', 31, 'kyu', 5, 'Sensei Lopez', 'Krav Maga Dojo'),
('Allen', 'James', 29, 'dan', 3, 'Sensei Wilson', 'Kickboxing Gym'),
('Young', 'Avery', 36, 'kyu', 6, 'Sensei Thomas', 'Wing Chun School'),
('Hernandez', 'Mia', 37, 'dan', 2, 'Sensei Moore', 'Capoeira Center'),
('King', 'Noah', 33, 'kyu', 4, 'Sensei Jackson', 'Tai Chi Studio'),
('Wright', 'Charlotte', 28, 'dan', 1, 'Sensei Davis', 'Escrima Dojo'),
('Scott', 'Liam', 34, 'kyu', 5, 'Sensei Thompson', 'Boxing Club'),
('Torres', 'Harper', 30, 'dan', 2, 'Sensei Garcia', 'Karate Dojo'),
('Nguyen', 'Ella', 39, 'dan', 2, 'Sensei Moore', 'Tai Chi Studio'),
('Hill', 'Logan', 38, 'kyu', 3, 'Sensei White', 'Escrima Dojo'),
('Flores', 'Sophia', 31, 'dan', 4, 'Sensei Harris', 'Boxing Club'),
('Green', 'Ethan', 37, 'kyu', 5, 'Sensei Martin', 'Karate Dojo'),
('Adams', 'Mason', 36, 'dan', 6, 'Sensei Thompson', 'Taekwondo Dojo'),
('Nelson', 'Ava', 32, 'kyu', 1, 'Sensei Lee', 'Jiu-Jitsu Academy'),
('Baker', 'Daniel', 41, 'dan', 2, 'Sensei Rodriguez', 'Aikido Dojo'),
('Hall', 'Olivia', 30, 'kyu', 3, 'Sensei Davis', 'Kendo Club'),
('Ramirez', 'Elijah', 39, 'dan', 4, 'Sensei Hernandez', 'Muay Thai Gym'),
('Campbell', 'Mia', 38, 'kyu', 5, 'Sensei Thompson', 'Boxing Club'),
('Mitchell', 'Ethan', 33, 'dan', 6, 'Sensei Martin', 'Wrestling Academy'),
('Roberts', 'Isabella', 31, 'kyu', 1, 'Sensei Lee', 'MMA Gym'),
('Carter', 'James', 40, 'dan', 2, 'Sensei Rodriguez', 'Tang Soo Do Dojo'),
('Phillips', 'Avery', 29, 'kyu', 3, 'Sensei Thomas', 'Judo Club'),
('Evans', 'Mia', 38, 'dan', 4, 'Sensei Moore', 'Hapkido Academy'),
('Turner', 'Noah', 36, 'kyu', 5, 'Sensei Jackson', 'Krav Maga Dojo'),
('Torres', 'Charlotte', 34, 'dan', 6, 'Sensei Thompson', 'Kickboxing Gym'),
('Parker', 'Liam', 35, 'kyu', 1, 'Sensei Davis', 'Wing Chun School'),
('Collins', 'Harper', 39, 'dan', 2, 'Sensei Garcia', 'Capoeira Center'),
('Edwards', 'Ella', 32, 'kyu', 3, 'Sensei Hernandez', 'Tai Chi Studio'),
('Stewart', 'Logan', 37, 'dan', 4, 'Sensei Thompson', 'Escrima Dojo'),
('Sanchez', 'Sophia', 30, 'kyu', 5, 'Sensei Davis', 'Boxing Club'),
('Morris', 'Ethan', 39, 'dan', 6, 'Sensei Garcia', 'Karate Dojo'),
('Rogers', 'Mason', 36, 'kyu', 1, 'Sensei Martin', 'Taekwondo Dojo'),
('Reed', 'Ava', 33, 'dan', 2, 'Sensei Rodriguez', 'Jiu-Jitsu Academy'),
('Cook', 'Daniel', 32, 'kyu', 3, 'Sensei Thompson', 'Aikido Dojo'),
('Morgan', 'Olivia', 31, 'dan', 4, 'Sensei Davis', 'Kendo Club'),
('Bell', 'Elijah', 38, 'kyu', 5, 'Sensei Hernandez', 'Muay Thai Gym'),
('Murphy', 'Mia', 35, 'dan', 6, 'Sensei Thompson', 'Boxing Club'),
('Bailey', 'Ethan', 34, 'kyu', 1, 'Sensei Lee', 'Wrestling Academy'),
('Rivera', 'Isabella', 32, 'dan', 2, 'Sensei Rodriguez', 'MMA Gym'),
('Cooper', 'James', 39, 'kyu', 3, 'Sensei Thomas', 'Tang Soo Do Dojo'),
('Richardson', 'Avery', 36, 'dan', 4, 'Sensei Moore', 'Judo Club'),
('Cox', 'Mia', 31, 'kyu', 5, 'Sensei Jackson', 'Hapkido Academy'),
('Ward', 'Noah', 30, 'dan', 6, 'Sensei Thompson', 'Krav Maga Dojo'),
('Peterson', 'Charlotte', 33, 'kyu', 1, 'Sensei Davis', 'Kickboxing Gym'),
('Kelly', 'Liam', 40, 'dan', 2, 'Sensei Garcia', 'Wing Chun School'),
('Gray', 'Harper', 37, 'kyu', 3, 'Sensei Hernandez', 'Capoeira Center'),
('Ramirez', 'Ella', 36, 'dan', 4, 'Sensei Thompson', 'Tai Chi Studio'),
('James', 'Logan', 35, 'kyu', 5, 'Sensei Davis', 'Escrima Dojo'),
('Watson', 'Sophia', 34, 'dan', 6, 'Sensei Garcia', 'Boxing Club'),
('Brooks', 'Ethan', 39, 'kyu', 1, 'Sensei Martin', 'Karate Dojo'),
('Sanders', 'Mason', 32, 'dan', 2, 'Sensei Rodriguez', 'Taekwondo Dojo'),
('Price', 'Ava', 33, 'kyu', 3, 'Sensei Thompson', 'Jiu-Jitsu Academy'),
('Coleman', 'Daniel', 38, 'dan', 4, 'Sensei Davis', 'Aikido Dojo'),
('Long', 'Olivia', 31, 'kyu', 5, 'Sensei Hernandez', 'Kendo Club'),
('Foster', 'Elijah', 40, 'dan', 6, 'Sensei Thompson', 'Muay Thai Gym'),
('Bennett', 'Mia', 37, 'kyu', 1, 'Sensei Moore', 'Boxing Club'),
('Washington', 'Isabella', 36, 'dan', 2, 'Sensei Garcia', 'Wrestling Academy'),
('Butler', 'James', 30, 'kyu', 3, 'Sensei Thompson', 'MMA Gym'),
('Simmons', 'Avery', 31, 'dan', 4, 'Sensei Davis', 'Tang Soo Do Dojo'),
('Foster', 'Mia', 32, 'kyu', 5, 'Sensei Hernandez', 'Judo Club'),
('Gonzalez', 'Noah', 39, 'dan', 6, 'Sensei Thompson', 'Hapkido Academy'),
('Bryant', 'Charlotte', 38, 'kyu', 1, 'Sensei Davis', 'Krav Maga Dojo'),
('Alexander', 'Liam', 35, 'dan', 2, 'Sensei Garcia', 'Kickboxing Gym'),
('Russell', 'Harper', 34, 'kyu', 3, 'Sensei Thompson', 'Wing Chun School'),
('Griffin', 'Ella', 33, 'dan', 4, 'Sensei Davis', 'Capoeira Center'),
('Diaz', 'Logan', 32, 'kyu', 5, 'Sensei Hernandez', 'Tai Chi Studio'),
('Hayes', 'Sophia', 31, 'dan', 6, 'Sensei Thompson', 'Escrima Dojo'),
('Myers', 'Ethan', 40, 'kyu', 1, 'Sensei Garcia', 'Boxing Club'),
('Brooks', 'Mason', 37, 'dan', 2, 'Sensei Thompson', 'Karate Dojo');


CREATE USER 'myuser'@'localhost' IDENTIFIED BY '123456789';

GRANT ALL PRIVILEGES ON Karate.* TO 'myuser'@'localhost';




CREATE LOGIN myuser   
    WITH PASSWORD = '123456789';  
CREATE USER myuser FOR LOGIN myuser; 



